[package]
name = "capnp-nonblock"
version = "0.1.0"
authors = ["Dan Burkert <dan@danburkert.com>"]
description = "Cap'n Proto serialization on non-blocking streams"

[dependencies]
nom = { git = "https://github.com/Geal/nom.git" }
capnp = "0.5"
byteorder = "0.4"

[dev-dependencies]
capnp = { version = "0.5", features = ["quickcheck"] }
quickcheck = "0.2"
